name: C++ CI

on:
  push

jobs:
  test:
    name: Tests in ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [ Release, Debug, RelWithDebInfo ]
        compiler: [ gcc, clang ]

    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: sudo apt install binutils clang g++ cmake valgrind

      - name: Build main
        run: ./build.sh ${{ matrix.build_type }} ${{ matrix.compiler }}

      - name: Test main
        run: ./test.sh ${{ matrix.build_type }}

      - if: ${{ matrix.build_type == 'RelWithDebInfo' }}
        name: Test main with valgrind
        run: ./test-valgrind.sh
